		#INCLUDE<P16F628.INC>
		__CONFIG 3F10
		
;DECLARACION DE ESPACIOS DE MEMORIA A USAR		
		CBLOCK	0X20
		D1
		D2
		D3
		D4
		AUX_W
		AUX_STATUS
		CONT_AR	
		CONT_AR_2
		STOP_REG
		ENDC		

;DECLARACION DE CONSTATNES
#DEFINE BTN_STOP_STEP 	PORTB,0
#DEFINE BTN_START 		PORTA,4

#DEFINE PIN_D1 	3
#DEFINE PIN_D2 	2
#DEFINE PIN_D3 	1
#DEFINE PIN_D4 	0

#DEFINE	PORT_DISPLAY	PORTA
#DEFINE	APAGAR_DISPLAYS CLRF	PORTA
#DEFINE STOP_FLAG	STOP_REG, 0

;DECLARACION DE MACROS

MOSTRAR	MACRO	DIGITO,PIN
		APAGAR_DISPLAYS
		MOVF	DIGITO,W
		CALL	TAB_DISPLAY
		MOVWF	PORTB
		BSF		PORT_DISPLAY,PIN
		ENDM

SUMAR	MACRO	DIGITO
		INCF	DIGITO,1
		MOVF	DIGITO,W
		XORLW	.9
		BTFSC	STATUS,Z
		CLRF	DIGITO
		ENDM

;INICIO DEL PROGRAMA		
		
		ORG		0X00
		GOTO	CONFI
		ORG		0X04		

;RUTINA DE INTERRUPCION
;DESBORDA EL TIMER CADA 15ms
;MUESTRA TODOS LOS DIGITOS DE ACUERDO A LAS VARIABLES D1:4

;GUARDA STATUS Y W EN VARIABLES AUXILIARES
		BCF		INTCON,T0IF
		BCF		INTCON,GIE		
		MOVWF	AUX_W
		MOVLW	STATUS
		MOVWF	AUX_STATUS
;MULTIPLEXADO DE DISPLAYS
		BTFSC	PORT_DISPLAY,PIN_D1
		GOTO	MOSTRAR_D2			
		BTFSC	PORT_DISPLAY,PIN_D2
		GOTO	MOSTRAR_D3
		BTFSC	PORT_DISPLAY,PIN_D3
		GOTO	MOSTRAR_D4
		
		MOSTRAR	D1,PIN_D1
		GOTO 	FIN_T0I

MOSTRAR_D2
		MOSTRAR D2,PIN_D2
		GOTO 	FIN_T0I

MOSTRAR_D3
		MOSTRAR D3,PIN_D3
		GOTO 	FIN_T0I

MOSTRAR_D4
		MOSTRAR	D4,PIN_D4
		
FIN_T0I
;REINICIA TIMER Y RECUPERA STATUS Y W
		MOVLW	.198
		MOVWF	TMR0
		MOVF	AUX_STATUS,W
		MOVWF	STATUS
		MOVF	AUX_W,W
		RETFIE

;CONFIGURACION
		
CONFI
		MOVLW	0X07
		MOVWF	CMCON; CMCON SE TIENE QUE ESTABLECER EN 7 PARA USAR TODO EL PORTA
		MOVLW	.198
		MOVWF	TMR0
		BSF		STATUS,RP0
		MOVLW	b'00000001'
		MOVWF	TRISB	
		MOVLW	b'11110000'
		MOVWF	TRISA
		BCF		OPTION_REG,T0CS
		BCF		OPTION_REG,PSA
		BSF		OPTION_REG,PS0
		BSF		OPTION_REG,PS1
		BSF		OPTION_REG,PS2
		BSF		INTCON,GIE
		BSF		INTCON,T0IE
		BCF		STATUS,RP0

;RUTINA PRINCIPAL
;INCREMENTA DE 0 A 9 CADA DIGITO DEPENDIENDO QUE BOTÓN SE TOCA. 

		CLRF	PORTA
		CLRF	PORTB
		CLRF	D4
		MOVLW	.1
		MOVWF	D3
		MOVLW	.2
		MOVWF	D2
		MOVLW	.3
		MOVWF	D1
		BSF		STOP_FLAG
		
STOP	BTFSC	BTN_STOP_STEP
		GOTO	START
		BTFSS	BTN_START
		GOTO	STOP
		BCF		STOP_FLAG

START	SUMAR	D1
		SUMAR	D2
		SUMAR	D3
		SUMAR	D4
		CALL 	DEMORA
		CALL 	DEMORA

		BTFSC	BTN_STOP_STEP
		BSF		STOP_FLAG
		BTFSS	STOP_FLAG
		GOTO 	START
		GOTO	STOP


DEMORA
		MOVLW	.255
		MOVWF	CONT_AR
LOOP_AR
		MOVLW	.255
		MOVWF	CONT_AR_2
LOOP_AR_2
		DECFSZ	CONT_AR_2,1
		GOTO	LOOP_AR_2
		DECFSZ	CONT_AR,1
		GOTO	LOOP_AR
		RETURN
			
;CONVERSOR A DISPLAY
;RB1->SEG A
;RB2->SEG B 
;RB3->SEG C
;RB4->SEG D
;RB5->SEG E 
;RB6->SEG F
;RB7->SEG G

TAB_DISPLAY
		ADDWF	PCL,1
		;         GFEDCBA-
		RETLW	b'11011011'	
		RETLW	b'10111111'
		RETLW	b'10101001'
		RETLW	b'11110001'
		RETLW	b'00100001'
		RETLW	b'00000000'
		RETLW	b'00000000'
		RETLW	b'00000000'
		RETLW	b'00000000'
		
		END